# -*- coding: utf-8 -*-
"""Contains-Duplicate.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1p2vvcf13Q6fVYp5AMiYUs1QNfPxhGuJM
"""

def containsDuplicate(nums):
  nums.sort()
  for i in range(1, len(nums)):
    if nums[i] == nums[i-1]:
      return True
  return False

nums = [1,2,3,1]
containsDuplicate(nums)